### PR TITLE
Custom Classnames

### PR DESCRIPTION
**Pull request by alejonext**
Place this  library in production is required which can rename classes. Then decided that they can make these changes.

### CODE REVIEW

**Comment by pedrocorreia** [comment]
Hi @alejonext, not sure what do mean. Could you please describe what it is that your pull request does?

**Comment by alejonext** [comment]
Custom the classnames,

**Comment by pedrocorreia** [comment]
Dude, come on! 
I'm not gonna look at the diffs of your 9 commits. 
If you want us to consider your pull request, please give a decent description of what you've done.

**Comment by alejonext** [comment]
I do not understand, if the idea is that you can modify the farmework. Would not it be smarter than 85% of classnames, were variables? In fact many of the variables that you have on [file](https://github.com/sapo/Ink/blob/develop/src/sass/config/_classnames.scss#L93) are not used.

What I'm doing is putting all the variables so that they can be used. At the same time that can be modified.

**Comment by pedrocorreia** [comment]
I'm sorry, but I cannot merge this for the following reasons:
* You've added junk files in c0568e7;
* The changes you made are not consistent;
* You've changed class names in CSS that is used by component's without checking if there is a expectation on the JS side that these exist.

**Pull request closed without merging**
